# nixpacks.toml (Versión Corregida y Optimizada)

# --- Fase 1: Configuración del Entorno del Sistema ---
[phases.setup]
nixPkgs = [
    "python312Full",
    "gcc",
    "pkg-config",
]

# --- Fase 2: Instalación de Dependencias de Python ---
[phases.install]
cmds = [
    # Crea un entorno virtual autocontenido.
    "python -m venv /opt/venv",
    # Actualiza pip dentro del venv.
    "/opt/venv/bin/python -m pip install --upgrade pip",
    # Instala las dependencias del proyecto.
    "/opt/venv/bin/pip install -r requirements.txt"
]

# --- Fase 3: Construcción de la Aplicación ---
# Esta fase se ejecuta una vez por despliegue, después de la instalación.
# Es el lugar correcto para migraciones y collectstatic.
[phases.build]
cmds = [
    "/opt/venv/bin/python manage.py collectstatic --no-input --clear",
    "/opt/venv/bin/python manage.py migrate --no-input"
]

# --- Fase 4: Comando de Inicio ---
# Este comando solo inicia el servidor web.
[start]
cmd = "/opt/venv/bin/gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"