# nixpacks.toml

# --- Fase 1: Configuración del Entorno del Sistema ---
[phases.setup]
nixPkgs = [
    "python312Full",
    "gcc",
    "pkg-config",
]

# --- Fase 2: Instalación de Dependencias de Python ---
[phases.install]
cmds = [
    # Crea un entorno virtual autocontenido en la carpeta /opt/venv.
    "python -m venv /opt/venv",
    # Usa el pip de DENTRO del venv para instalar/actualizar pip.
    "/opt/venv/bin/python -m pip install --upgrade pip",
    # Usa el pip del venv para instalar todas tus dependencias.
    "/opt/venv/bin/pip install -r requirements.txt"
]

# --- Fase 3: Comando de Inicio ---
[start]
# Ejecuta gunicorn desde DENTRO del entorno virtual.
cmd = "/opt/venv/bin/python manage.py collectstatic --no-input && /opt/venv/bin/python manage.py migrate && /opt/venv/bin/gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"