# nixpacks.toml

[phases.setup]
nixPkgs = [
    # Usaremos la versión "Full" de Python para asegurar que trae todas las herramientas estándar.
    "python312Full",
    # ¡Esta es la corrección clave!
    # Instalamos 'pip' como un paquete del sistema usando Nix,
    # para que esté disponible para el intérprete de Python.
    "python312Packages.pip",
    # Dependencias necesarias para la compilación de mysqlclient.
    "pkg-config",
    "mariadb-connector-c"
]

[phases.install]
cmds = [
    # Ahora este comando debería funcionar porque Nix ya instaló 'pip'.
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"