[phases.setup]
nixPkgs = [
  "python312Full",
  "pkg-config",
  "mariadb-connector-c"
]

[phases.install]
cmds = [
  "python -m venv venv",
  "source venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "venv/bin/gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
