# Nixpacks Configuration

# Setup phase
[phases.setup]
nixPkgs = ["...", "libmysqlclient.dev", "gcc", "cairo", "python311Packages.cairocffi"]

# Install phase
[phases.install]
aptPkgs = ["...", "libcairo2", "libcairomm-1.0-1v5", "python3-cffi-backend", "cairosvg", "libglib2.0-0"]
nixLibs = ['...', "cairo", "gobject-introspection", "glib", "pango"]
cmds = [
    "python -m venv --copies /opt/venv", 
    ". /opt/venv/bin/activate", 
    "pip install -r requirements.txt",
    "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH",
    "echo 'Cairo library installation path:'"
]