# Generated by Django 5.2 on 2025-04-16 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('fundacion', models.DateField()),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
                ('campeonatos', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('ARQ', 'Arquero'), ('DEF', 'Defensor'), ('MED', 'Mediocampista'), ('DEL', 'Delantero'), ('DT', 'Director Técnico')], max_length=3)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('fecha_ingreso', models.PositiveIntegerField()),
                ('fecha_salida', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('R', 'Retirado'), ('T', 'Traspasado')], default='A', max_length=1)),
                ('goles_totales', models.PositiveIntegerField(default=0)),
                ('amarillas_totales', models.PositiveIntegerField(default=0)),
                ('rojas_totales', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historial.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('L', 'Local'), ('V', 'Visitante')], max_length=1)),
                ('goles_chabas', models.PositiveIntegerField(default=0)),
                ('goles_rival', models.PositiveIntegerField(default=0)),
                ('goleadores', models.ManyToManyField(related_name='goles_partidos', through='historial.Gol', to='historial.jugador')),
                ('rival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historial.club')),
            ],
        ),
        migrations.AddField(
            model_name='gol',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historial.partido'),
        ),
        migrations.CreateModel(
            name='TarjetaAmarilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historial.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historial.partido')),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='amarillas',
            field=models.ManyToManyField(related_name='amarillas_partidos', through='historial.TarjetaAmarilla', to='historial.jugador'),
        ),
        migrations.CreateModel(
            name='TarjetaRoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historial.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historial.partido')),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='rojas',
            field=models.ManyToManyField(related_name='rojas_partidos', through='historial.TarjetaRoja', to='historial.jugador'),
        ),
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historial.torneo'),
        ),
    ]
