# Generated by Django 5.0.6 on 2025-05-20 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_partido_arbitro_partido_instancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='fecha_salida',
        ),
        migrations.CreateModel(
            name='ParticipacionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historial.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historial.torneo')),
            ],
            options={
                'unique_together': {('jugador', 'torneo')},
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='torneos',
            field=models.ManyToManyField(blank=True, through='historial.ParticipacionJugador', to='historial.torneo'),
        ),
    ]
