# Generated by Django 5.0.6 on 2025-05-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0003_remove_jugador_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
