# Generated by Django 5.1.2 on 2025-07-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0004_partido_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='jugado',
            field=models.BooleanField(default=False, help_text='Marcar si el partido ya fue jugado'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
