# Generated by Django 5.1.2 on 2025-07-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0005_partido_jugado_alter_partido_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='jugado',
            field=models.BooleanField(default=True, help_text='Marcar si el partido ya fue jugado'),
        ),
    ]
