# Generated by Django 5.0.6 on 2025-07-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0006_alter_partido_jugado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('ARQ', 'Arquero'), ('DEF', 'Defensor'), ('MED', 'Mediocampista'), ('DEL', 'Delantero'), ('DT', 'Director Técnico'), ('SD', 'Sin Definir')], max_length=3),
        ),
    ]
