# Generated by Django 5.2.4 on 2025-08-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0008_partido_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='escudo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
