# Generated by Django 5.2.4 on 2025-09-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0009_alter_club_escudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_youtube', models.URLField(help_text='URL del video de YouTube')),
                ('clasificacion', models.CharField(choices=[('Completo', 'Partido Completo'), ('Resumen', 'Resumen'), ('Goles', 'Goles'), ('Otros', 'Otros')], default='Resumen', help_text='Clasificación del video (ej. Partido Completo, Resumen)', max_length=10)),
                ('titulo', models.CharField(blank=True, help_text='Título opcional para el video', max_length=200, null=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='historial.partido')),
            ],
        ),
    ]
