# Generated by Django 5.2.4 on 2026-01-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0010_videopartido'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('fundacion', 'Fundación'), ('infraestructura', 'Infraestructura'), ('campeonato', 'Campeonato'), ('partido_historico', 'Partido Historico'), ('logro', 'Logro deportivo'), ('otro', 'Otro')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='historia/')),
                ('destacado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
