# Generated by Django 5.2.4 on 2026-01-09 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0011_hitohistorico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hitohistorico',
            name='destacado',
        ),
        migrations.AddField(
            model_name='hitohistorico',
            name='partido',
            field=models.ForeignKey(blank=True, help_text='Partido relacionado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='historial.partido'),
        ),
        migrations.AlterField(
            model_name='hitohistorico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='hitos/'),
        ),
        migrations.AlterField(
            model_name='hitohistorico',
            name='tipo',
            field=models.CharField(choices=[('fundacion', 'Fundación'), ('cancha', 'Cancha'), ('partido', 'Partido histórico'), ('campeonato', 'Campeonato'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hitohistorico',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
