# Generated by Django 5.2.4 on 2026-02-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0012_remove_hitohistorico_destacado_hitohistorico_partido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='jugado',
        ),
        migrations.AddField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('J', 'Jugado'), ('P', 'Próximo'), ('V', 'En vivo')], default='P', max_length=1),
        ),
    ]
