# Generated by Django 5.2.4 on 2026-02-23 17:12

from django.db import migrations

def marcar_como_jugados(apps, schema_editor):
    Partido = apps.get_model('historial', 'Partido') # Reemplaza 'historial' por el nombre de tu app
    # Actualiza todos los partidos que existen hasta ahora a Jugado ('J')
    Partido.objects.all().update(estado='J')

class Migration(migrations.Migration):
    dependencies = [
        ('historial', 'nombre_de_tu_migracion_anterior'), # Esto se pone solo
    ]

    operations = [
        migrations.RunPython(marcar_como_jugados),
    ]