# Generated by Django 5.2.4 on 2026-03-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0014_corregir_estados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videopartido',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='videopartido',
            name='orden',
            field=models.PositiveIntegerField(default=1, help_text='Orden de aparición (ej: 1 para parte 1)'),
        ),
    ]
