# Generated by Django 5.2.4 on 2026-03-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0015_alter_videopartido_options_videopartido_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videopartido',
            options={'ordering': ['-fecha', 'orden']},
        ),
        migrations.AddField(
            model_name='videopartido',
            name='fecha',
            field=models.DateField(blank=True, help_text='Si se vincula a un partido, se usará la fecha de este automáticamente.', null=True),
        ),
        migrations.AlterField(
            model_name='videopartido',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_archivo', to='historial.partido'),
        ),
        migrations.AlterField(
            model_name='videopartido',
            name='url_youtube',
            field=models.URLField(help_text='Pegá la URL completa (propia o ajena)'),
        ),
    ]
